### ISSUE TITLE
How to subscribe the IoTAgent to the MQTT Broker?

### ISSUE THREAD

**Issue by garvi-x** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#13]
How to subscribe the IoTAgent to the MQTT Broker?

I am searching in configuration files how to subscribe the IoTAgent to the MQTT Broker of LoraServer.io, but I don't found it.

Thank in advance!! :grinning: And I'm sorry for my english.

**Comment by garvi-x** [comment]
Hello!! Good morning!

I've been seeing that data stored in the MQTT broker, but the IoTA isn't informed.

I'm still waiting for an answer. Thank you!

**Comment by garvi-x** [comment]
That's right. I was looking a parameter like mongodb, and I was understanding that application_server referred to loraserver's ip, not the ip of mqtt broker.

Now, I've included the internal_attributes parameter as follows:
`types: {
        LoraDevice: {
            service: 'weather',
            subservice: '/mini',
            internalAttributes: {
                lorawan: {
                    application_server: {
                        host: '192.168.1.66',
                        provider: 'loraserver.io'
                    },
                    application_id: '****',
                    app_eui: '****************',
                    application_key: '*******************************'
                }
            }
        }
    }`

But in the iotagent-lora log shows the following message:
`iotagent-lora_1  | info: New message in topic application/****/node/***************/rx
iotagent-lora_1  | info: LoRaWAN device unprovisioned
iotagent-lora_1  | error:  name=DUPLICATE_DEVICE_ID, message=A device with the same pair (Service, DeviceId) was found:clon-miniweather, code=409
`

**Comment by dcalvoalonso** [comment]
Could you please share the result of doing a GET to `/iot/devices` and to `/iot/services`?

**Comment by garvi-x** [comment]
Of course...


Devices
```
{
    "count": 1,
    "devices": [
        {
            "device_id": "clon-miniweather",
            "service": "weather",
            "service_path": "/mini",
            "entity_name": "clon-miniweather:LoraDevice",
            "entity_type": "LoraDevice",
            "attributes": [
                {
                    "object_id": "relative_humidity",
                    "name": "relative_humidity",
                    "type": "Number"
                },
                {
                    "object_id": "temperature",
                    "name": "temperature",
                    "type": "Number"
                }
            ],
            "internal_attributes": {
                "lorawan": {
                    "application_server": {
                        "host": "192.168.1.66",
                        "username": "iota_lw",
                        "password": "250802hopu",
                        "provider": "loraserver.io"
                    },
                    "application_id": "1",
                    "app_eui": "70B3D57ED000B60A",
                    "application_key": "2192ac97b12a2ff3c25f2d9b5ccb6ce9",
                    "data_model": "cayennelpp",
                    "dev_eui": "3738363779378704"
                }
            }
        }
    ]
}
```

Services 
```
{
    "name": "DEVICE_GROUP_NOT_FOUND",
    "message": "Couldn\t find device group for fields: weather and values: /mini"
}
```



This means that I need to create a group for this devices?

I forgot tell you that I'm using the static configuration for declare my types and I supposed it was implicit.

**Comment by dcalvoalonso** [comment]
I that case, you don't need to the device provisioning. The agent will automatically subscribe to the MQTT broker of the LoRaServer.io following your configuration file and devices will be provisioned automatically the first time data is received.

I suggest you clean your MongoDB DB and to try again.

**Comment by garvi-x** [comment]
I think I misexplained, I don't use a device provisioning. I use only a static configuration. 

> The agent will automatically subscribe to the MQTT broker of the LoRaServer.io following your configuration file and devices will be provisioned automatically the first time data is received.

Right, but when the IoTA receives new data, it tries to provision the device once again and fails because the device is already provisioned.

Equally I will try what you say.

**Comment by dcalvoalonso** [comment]
Have you achieve to solve this @garvi-x ?

**Comment by garvi-x** [comment]
Unfortunately I not achieve that the IoTAgent not to try to add the device every time the broker MQTT sends an update.

**Comment by dcalvoalonso** [comment]
Ok,I will review the integration with LoRaSever.io and let you know if I find any problem.

**Comment by garvi-x** [comment]
Hello Daniel,

I forged your repository and designed a solution for my problem.  If it's okay with you, you can validate (or not) my solution and I will collaborate with it.

Thank you for your help.

**Comment by dcalvoalonso** [comment]
@garvi-x Contributions are welcome!! :) Could you open a PR?

**Comment by garvi-x** [comment]
Of course! :))

**Comment by garvi-x** [comment]
> Ok,I will review the integration with LoRaSever.io and let you know if I find any problem.

Any progress?

**Comment by dcalvoalonso** [comment]
Sorry @garvi-x but I am quite busy at this time. I will try to review the PR as soon as possible (hopefully next week)

**Comment by garvi-x** [comment]
Ok, no problem. It's not urgent so there's no rush. :))
