### ISSUE TITLE
there are multiple contribution policies

### ISSUE THREAD

**Issue by chicco785** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#130]
https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/blob/201ea252995d3b55de74a03bf1f528e93c6a851e/ContributionPolicy.txt

https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/blob/master/entity-cla_IoTAgent-Atos.pdf

the last one is the one proposed by FIWARE, so I guess the preferred one, but should be updated to allow for automated signature as introduced by PR #127

**Comment by chicco785** [comment]
to update the policy, the text:

To make this document effective, please sign it and upload it not GitHub as a Pull Request.

should be replaced by:

To make this document effective, please sign it by stating in a comment of your Github Pull
Request “I have read the CLA Document and I hereby sign the CLA”.

**Comment by cpezuela** [comment]
Update
[entity-cla_IoTAgent-Atos.pdf](https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/files/8305134/entity-cla_IoTAgent-Atos.pdf)
d

**Comment by cpezuela** [comment]
Replace by new file
