### ISSUE TITLE
Wrong reference to lorawan configuration

### ISSUE THREAD

**Issue by reitsma** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#24]
In dataTranslationService.toNgsi() line 43 the lorawan configuration property is looked up. The line should be:

`lorawanConf = device.internalAttributes[i].lorawan;`

In other places the internalAttributes are needed, but not here. 
This causes a problem when using a group configuration, because then the internalAttributes are returned as an array (from Mongo I suppose).

**Comment by dcalvoalonso** [comment]
Thanks for having detect this issues. It should be fixed with https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/pull/29

I have added some tests also to validate this.

Do you think that we can close this now?

**Comment by reitsma** [comment]
Sure. Let me try that too...
