### ISSUE TITLE
[MUST] Every GE must have training materials

### ISSUE THREAD

**Issue by jason-fox** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#38]
At the moment this enabler has no Tutorial and no link to the Academy and does not fulfil the minimum **Training** section requirements. 

The suggestion is to create a simple *Attaching other IoT Agents tutorial*  to provide a series of simple hello world connections for each agent in turn - this needs to include 

* One docker compose file for base config
* A set of REST API calls to provision the service
* An indication on how to make  minimal measure arrive (e.g. publishing an MQTT topic or equivalent)
* Proof that the data arrives in Orion.

- Presence of training  is a MUST requirement

**Comment by dcalvoalonso** [comment]
Hi @jason-fox , what about https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/blob/master/docs/tutorialStm32TTN.md?

**Comment by jason-fox** [comment]
@dcalvoalonso  -  That would be fine, it just needs to be properly linked and exposed in the academy

Could you assign  this Issues to me and leave it **open** for now (so it doesn't get lost) and I'll add it to the academy in a standard format.

**Comment by dcalvoalonso** [comment]
It is done! :)
