### ISSUE TITLE
Consider publish documentation to readthedocs

### ISSUE THREAD

**Issue by jmcanterafonseca** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#4]

**Comment by dcalvoalonso** [comment]
Finally fixed with 3c8c11ec459d3501d622f9cc185977ff72464868

Documentation is available at http://iot-agent-lorawan.readthedocs.io/en/latest/

Corresponding badge has been also added to https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN
