### ISSUE TITLE
[MUST] Show versioned documentation

### ISSUE THREAD

**Issue by jason-fox** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#48]
On the IoT LoRaWAN Agent ReadtheDocs project, no versioned documentation is displayed

- Goto https://readthedocs.org/projects/fiware-lorawan/versions/
- Ensure that **active** checkmark is ticked against relevant release tags

**Comment by dcalvoalonso** [comment]
It is done @jason-fox;
- https://fiware-lorawan.readthedocs.io/en/fiware_7.5.1/
- https://fiware-lorawan.readthedocs.io/en/fiware_7.5/

Do you know if there is a way to automatically configure RTD to produce documentation for release tags?

**Comment by dcalvoalonso** [comment]
@jason-fox, could you please check if this issue can be closed? Thanks! :)
