### ISSUE TITLE
Docker releases?

### ISSUE THREAD

**Issue by taliaga** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#58]
Hi! 
I noticed the [official docker image](https://hub.docker.com/r/fiware/iotagent-lorawan/) linked in the README is 6 months old now. Two questions: 
- Do you plan to add automated docker builds?
- Is there a versioning schema for the this Agent? (to know if I should update and to which version, etc.)

Thanks in advance!

**Comment by dcalvoalonso** [comment]
I have contacted @jason-fox and the FIWARE Foundation team to see what's happening with the Docker image. I will try to provide an update as soon as possible.

**Comment by dcalvoalonso** [comment]
Some comments regarding this issue: we have started to use https://github.com/semantic-release/semantic-release: ` it automates the whole package release workflow including: determining the next version number, generating the release notes and publishing the package`.

From now, every time new changes are merged in the master branch, automatically this process will be run.

THE FIWARE Foundation team is working to update the LoRaWAN docker image. I will close the issue when this is done.

**Comment by dcalvoalonso** [comment]
As you can see in https://hub.docker.com/r/fiware/iotagent-lorawan/tags, the Docker image has been updated.
Please note that this Docker image will be rebuilt only for stable versioned versions.

**Comment by dcalvoalonso** [comment]
@taliaga , would be OK for you to close the issue?

**Comment by taliaga** [comment]
Sure thing!. So, I understand the FIWARE Foundation will take care of the automatic builds of docker images as new versions come out. That's great news.
