### ISSUE TITLE
possible bug in the toNGSI translation

### ISSUE THREAD

**Issue by chicco785** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#63]
looking at this code:
https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/blob/master/lib/dataTranslationService.js#L83

shouldn't be:
`name: device.active[i].name` ?

if I recall right, "name" is what we want to be the attribute in NGSI, but hey, I haven't tested it, it's just a guess reading the code

**Comment by dcalvoalonso** [comment]
I close this issue. @chicco785 If you find further evidence related to it, please open it again.
