### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by jomarequena** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#7]
good afternoon,

We are trying to integrate ttn with fiware and we are having problems when it comes to lifting it, you can help us.

[centos@orion-uah IoTagent-LoRaWAN-master]$ node bin/iotagent-lora
time=2018-09-07T11:13:39.621Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=Activating IOT Agent NGSI Library. | comp=IoTAgent
time=2018-09-07T11:13:39.624Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.Global | srv=n/a | subsrv=n/a | msg=MongoDB Device registry selected for NGSI Library | comp=IoTAgent
time=2018-09-07T11:13:39.648Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=First connection attempt | comp=IoTAgent
time=2018-09-07T11:13:39.649Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Attempting to connect to MongoDB instance. Attempt 1 | comp=IoTAgent
time=2018-09-07T11:13:39.679Z | lvl=ERROR | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=MONGODB-001: Error trying to connect to MongoDB: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED ::1:27017] | comp=IoTAgent
time=2018-09-07T11:13:39.679Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Waiting 5 seconds before attempting again. | comp=IoTAgent
time=2018-09-07T11:13:44.685Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Attempting to connect to MongoDB instance. Attempt 2 | comp=IoTAgent
time=2018-09-07T11:13:44.702Z | lvl=ERROR | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=MONGODB-001: Error trying to connect to MongoDB: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED ::1:27017] | comp=IoTAgent
time=2018-09-07T11:13:44.703Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Waiting 5 seconds before attempting again. | comp=IoTAgent
time=2018-09-07T11:13:49.711Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Attempting to connect to MongoDB instance. Attempt 3 | comp=IoTAgent
time=2018-09-07T11:13:49.778Z | lvl=ERROR | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=MONGODB-001: Error trying to connect to MongoDB: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED ::1:27017] | comp=IoTAgent
time=2018-09-07T11:13:49.778Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Waiting 5 seconds before attempting again. | comp=IoTAgent
time=2018-09-07T11:13:54.782Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Attempting to connect to MongoDB instance. Attempt 4 | comp=IoTAgent
time=2018-09-07T11:13:54.803Z | lvl=ERROR | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=MONGODB-001: Error trying to connect to MongoDB: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED ::1:27017] | comp=IoTAgent
time=2018-09-07T11:13:54.804Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Waiting 5 seconds before attempting again. | comp=IoTAgent
time=2018-09-07T11:13:59.832Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=Attempting to connect to MongoDB instance. Attempt 5 | comp=IoTAgent
time=2018-09-07T11:13:59.839Z | lvl=ERROR | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=MONGODB-001: Error trying to connect to MongoDB: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED ::1:27017] | comp=IoTAgent
**time=2018-09-07T11:13:59.839Z | lvl=ERROR | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DbConn | srv=n/a | subsrv=n/a | msg=MONGODB-002: Error found after [5] attempts: MongoError: failed to connect to server [localhost:27017] on first connect [MongoError: connect ECONNREFUSED ::1:27017] | comp=IoTAgent**
time=2018-09-07T11:13:59.843Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.NorthboundServer | srv=n/a | subsrv=n/a | msg=Starting IoT Agent listening on port [4061] | comp=IoTAgent
time=2018-09-07T11:13:59.844Z | lvl=DEBUG | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.NorthboundServer | srv=n/a | subsrv=n/a | msg=Using config:

{
    "logLevel": "DEBUG",
    "timestamp": true,
    "contextBroker": {
        "host": "localhost",
        "port": "1026",
        "ngsiVersion": "v2",
        "url": "http://localhost:1026"
    },
    "server": {
        "port": 4061
    },
    "defaultResource": "/iot/d",
    "deviceRegistry": {
        "type": "mongodb"
    },
    "mongodb": {
        "host": "localhost",
        "port": "27017",
        "db": "orion-uah"
    },
    "types": {},
    "service": "howtoService",
    "subservice": "/howto",
    "providerUrl": "http://localhost:4061",
    "deviceRegistrationDuration": "P1Y",
    "defaultType": "Thing"
}
 | comp=IoTAgent
time=2018-09-07T11:13:59.866Z | lvl=INFO | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.ContextServer | srv=n/a | subsrv=n/a | msg=Loading NGSI Contect server routes | comp=IoTAgent
time=2018-09-07T11:13:59.869Z | lvl=DEBUG | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.ContextServer | srv=n/a | subsrv=n/a | msg=Loading access validation Templates | comp=IoTAgent
info: iotagent-node-lib activated
info: Loading types from configuration file
info: Loading services from registry
**time=2018-09-07T11:13:59.898Z | lvl=ERROR | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DomainControl | srv=n/a | subsrv=n/a | msg=TypeError: Cannot read property 'find' of undefined | comp=IoTAgent
time=2018-09-07T11:13:59.899Z | lvl=DEBUG | corr=d32e1352-b214-4d21-a70b-9e3619d30622 | trans=d32e1352-b214-4d21-a70b-9e3619d30622 | op=IoTAgentNGSI.DomainControl | srv=n/a | subsrv=n/a | msg=response-time: 21036 | comp=IoTAgent**

Y mongo esta disponible:

[centos@orion-uah ~]$ netstat -na | grep 27017
tcp        0      0 127.0.0.1:27017             0.0.0.0:*                   LISTEN
tcp        0      0 127.0.0.1:33415             127.0.0.1:27017             ESTABLISHED
tcp        0      0 127.0.0.1:27017             127.0.0.1:33415             ESTABLISHED
unix  2      [ ACC ]     STREAM     LISTENING     78483795 /tmp/mongodb-27017.sock
[centos@orion-uah ~]$ mongo
MongoDB shell version: 3.2.6
connecting to: test
Server has startup warnings:
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten]
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten]
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten]
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. rlimits set to 1024 processes, 64000 files. Number of processes should be at least 32000 : 0.5 times number of files.
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten]
> show dbs
local      0.000GB
orion      0.000GB
orion-uah  0.000GB

**Comment by dcalvoalonso** [comment]
Hi @jomarequena ,

From your logs I understand that you are not using the docker images, aren't you?

Could you please share your nodejs version?

Thanks,

Daniel

**Comment by jomarequena** [comment]
Hi Daniel,

No, I downloaded https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN.git about my Fiware virtual machine created with the image orion-psb-image-R5.4. In it, I have installed the nodejs version:

[centos@orion-uah ~]$ node -v
v6.14.4

Thank you very much!

**Comment by jomarequena** [comment]
Yes, It's ready. But iotagento not started.

[centos@orion-uah ~]$ mongo --port 27017
MongoDB shell version: 3.2.6
connecting to: 127.0.0.1:27017/test
Server has startup warnings:
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten]
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten]
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten]
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten] ** WARNING: soft rlimits too low. rlimits set to 1024 processes, 64000 files. Number of processes should be at least 32000 : 0.5 times number of files.
2018-09-06T20:41:15.667+0000 I CONTROL  [initandlisten]
> show dbs
local      0.000GB
orion      0.000GB
orion-uah  0.000GB
>

Thanks.

**Comment by dcalvoalonso** [comment]
This is quite strange because nobody has reported this kind of error yet and the connection to the MongoDB instance is part of the https://github.com/telefonicaid/iotagent-node-lib, which is common to all the agents.

Could you please do the same test in your local environment or try to use docker?

**Comment by dcalvoalonso** [comment]
There were a couple of very minor errors in your JSON payload. Please use the following one:

```
{
	"devices": [{
		"device_id": "tfmiot_prototipo_nodobonzo",
		"entity_name": "tfmiot_prototipo_nodobonzo",
		"entity_type": "LoraDevice",
		"timezone": "Europe/Madrid",
		"attributes": [{
				"object_id": "bp",
				"name": "presion",
				"type": "Number"
			},
			{
				"object_id": "day",
				"name": "day",
				"type": "Integer"
			},
			{
				"object_id": "month",
				"name": "month",
				"type": "Integer"
			},
			{
				"object_id": "year",
				"name": "year",
				"type": "Integer"
			},
			{
				"object_id": "hour",
				"name": "hour",
				"type": "Integer"
			},
			{
				"object_id": "minute",
				"name": "minute",
				"type": "Integer"
			},
			{
				"object_id": "second",
				"name": "second",
				"type": "Integer"
			},
			{
				"object_id": "rh",
				"name": "relative_humidity",
				"type": "Number"
			},
			{
				"object_id": "t",
				"name": "temperature",
				"type": "Number"
			},
			{
				"object_id": "bateria",
				"name": "nivel_carga",
				"type": "Number"
			}
		],
		"internal_attributes": {
			"lorawan": {
				"application_server": {
					"host": "eu.thethings.network",
					"username": "nodobonzo_tfmiot",
					"password": "ttn-account-v2.jNjJEPbSgjRPN44p3_B0SXNiuxXTCuW0Ob05fnYc***",
					"provider": "TTN"
				},
				"dev_eui": "006B579133ED7384",
				"app_eui": "70B3D57ED0011F99",
				"application_id": "nodobonzo_tfmiot",
				"application_key": "72CB543BC7342252199E42E17B8A0***",
				"data_model": "cayennelpp"
			}
		}
	}]
}
```

**Comment by dcalvoalonso** [comment]
As you can see in the log file:

```
iotagent-lora_1 | info: Decoding CaynneLPP message:AWgBaQJzbbMDZwNnBAAUBQAVBgAeAgcCDQ==
iotagent-lora_1 | error: Error decoding CaynneLPP message:Error: Invalid CayennLpp channel
iotagent-lora_1 | error: Could not cast message to NGSI
```

The problem now is that your CayenneLpp seems not to be valid. I have checked it and the problems are that you are using channel number above 100 which is not possible in our current implementation. There is also a problem with the size of the message since you are trying to use more than 11 bytes. You should split the message in two parts.

**Comment by dcalvoalonso** [comment]
Dear @jomarequena , have you been able to solve this problem?

**Comment by dcalvoalonso** [comment]
Since this issue has not had any activity for more than seven days, I will close it.

Please, don't hesitate in re-open it if you consider necessary @jomarequena.
