### ISSUE TITLE
Documentation and docker-composer.yml files need to be updated

### ISSUE THREAD

**Issue by jfernandz** [Atos-Research-and-Innovation/IoTagent-LoRaWAN#98]
I'm comming from here https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/issues/92#issuecomment-633041646 

You have serious inconsistencies between your [web documentation](https://fiware-lorawan.readthedocs.io/en/latest/installationguide/index.html), your [`README.md`](https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/blob/master/docker/README.md) and your suggested [`docker-compose.yml`](https://github.com/Atos-Research-and-Innovation/IoTagent-LoRaWAN/blob/master/docker/docker-compose.yml).

I think this needs to be fixed.

**Comment by cpezuela** [comment]
Thanks, merged in PR
